DECLARE @PRODID CHAR(5)
 
SET @PRODID = '414' --PRODID of product to remove
 
SELECT 'DROP TABLE ' + a.name 'DROPSTMT' FROM SYSOBJECTS a
INNER JOIN DYNAMICS.dbo.DU000010 b ON a.name=b.fileOSName
WHERE xtype = 'U' AND PRODID = @PRODID AND b.fileOSName NOT IN 
(SELECT fileOSName FROM DYNAMICS.dbo.DU000010 WHERE PRODID <> @PRODID)
UNION
SELECT 'DROP PROC ' + a.name FROM SYSOBJECTS a 
LEFT OUTER JOIN DYNAMICS.dbo.DU000010 b ON a.name LIKE 'zDP_'+RTRIM(b.fileOSName)+'%'
WHERE xtype = 'P' AND PRODID = @PRODID AND b.fileOSName NOT IN 
(SELECT fileOSName FROM DYNAMICS.dbo.DU000010 WHERE PRODID <> @PRODID)
ORDER BY DROPSTMT
 
-- DO THIS LAST!
DECLARE @PRODID CHAR(5)
 
SET @PRODID = '414' --PRODID of product to remove
 
DELETE DYNAMICS.dbo.DU000030 WHERE PRODID = @PRODID
DELETE DYNAMICS.dbo.DU000010 WHERE PRODID = @PRODID
DELETE DYNAMICS.dbo.DU000020 WHERE PRODID = @PRODID
DELETE DYNAMICS.dbo.DB_UPGRADE WHERE PRODID = @PRODID