SELECT p.vendorID, vendname, CASE WHEN VENDSTTS = 1 THEN 'Active' ELSE 'Inactive' END AS status FROM pm00200 p
WHERE VNDCLSID = 'EMPEXP'     
ORDER BY p.VENDORID



UPDATE pm00200 SET VENDSTTS = 2 WHERE vendorid = 'FLAHAUT'

--UPDATE pm00200 SET VENDSTTS = 0 WHERE VNDCLSID = 'EMPEXP' 


SELECT * FROM pm30200 WHERE VENDORID = 'METEREN' ORDER BY DOCDATE desc