SELECT * FROM (
SELECT TOP 10000 refrence, SUBSTRING(DSCRIPTN,8,LEN(DSCRIPTN)) AS ReportName, JRNENTRY, ORGNTSRC, ORPSTDDT, SUM(DEBITAMT) AS Amount FROM GL20000
WHERE REFRENCE LIKE '%,%' 
--HAVING SUM(DEBITAMT) != 0
GROUP BY REFRENCE,SUBSTRING(DSCRIPTN,8,LEN(DSCRIPTN)),JRNENTRY,ORGNTSRC, ORPSTDDT ORDER BY orgntsrc) a 

WHERE a.amount != 0






SELECT TOP 10000 refrence, DSCRIPTN, JRNENTRY, ORGNTSRC, * FROM GL20000
WHERE REFRENCE LIKE '%,%'



SELECT TOP 10000 refrence, JRNENTRY, ORGNTSRC, COUNT(*) FROM GL20000
WHERE REFRENCE LIKE '%,%'
GROUP BY REFRENCE,JRNENTRY,ORGNTSRC ORDER BY orgntsrc, REFRENCE