

select s.* INTO EPCO.dbo.EMPL_BANK_BACKUP_SY0600 FROM SY01200 p
join SY06000 s on s.VENDORID  = p.Master_ID
WHERE VENDORID IN  (SELECT VendorID FROM pm00200 WHERE VENDSTTS = 1 AND VNDCLSID = 'EMPEXP')

--(SELECT vendorID FROM pm00200 p2 WHERE p2.VENDSTTS = 1)

-- For employees where vendorID in (SELECT VendorID FROM pm00200 WHERE VENDSTTS = 1 AND VNDCLSID = 'EMPEXP')

-- for stuck EFT batches select * FROM dbo.cm20203
-- INTO EPCO.dbo.EMPL_BANK_BACKUP

INSERT INTO dbo.SY01200( Master_Type ,
       Master_ID ,
       ADRSCODE ,
       INET1 ,
       INET2 ,
       INET3 ,
       INET4 ,
       INET5 ,
       INET6 ,
       INET7 ,
       INET8 ,
       Messenger_Address ,
       INETINFO ,
       EmailToAddress ,
       EmailCcAddress ,
       EmailBccAddress) 

SELECT Master_Type ,
       Master_ID ,
       ADRSCODE ,
       INET1 ,
       INET2 ,
       INET3 ,
       INET4 ,
       INET5 ,
       INET6 ,
       INET7 ,
       INET8 ,
       Messenger_Address ,
       INETINFO ,
       EmailToAddress ,
       EmailCcAddress ,
       EmailBccAddress FROM EMPL_BANK_BACKUP_SY01200 WHERE Master_ID = 'HALLAHAN'


INSERT INTO sy06000 (SERIES ,
       CustomerVendor_ID ,
       ADRSCODE ,
       VENDORID ,
       CUSTNMBR ,
       EFTUseMasterID ,
       EFTBankType ,
       FRGNBANK ,
       INACTIVE ,
       BANKNAME ,
       EFTBankAcct ,
       EFTBankBranch ,
       GIROPostType ,
       EFTBankCode ,
       EFTBankBranchCode ,
       EFTBankCheckDigit ,
       BSROLLNO ,
       IntlBankAcctNum ,
       SWIFTADDR ,
       CustVendCountryCode ,
       DeliveryCountryCode ,
       BNKCTRCD ,
       CBANKCD ,
       ADDRESS1 ,
       ADDRESS2 ,
       ADDRESS3 ,
       ADDRESS4 ,
       RegCode1 ,
       RegCode2 ,
       BankInfo7 ,
       EFTTransitRoutingNo ,
       CURNCYID ,
       EFTTransferMethod ,
       EFTAccountType ,
       EFTPrenoteDate ,
       EFTTerminationDate)
SELECT	SERIES ,
       CustomerVendor_ID ,
       ADRSCODE ,
       VENDORID ,
       CUSTNMBR ,
       EFTUseMasterID ,
       EFTBankType ,
       FRGNBANK ,
       INACTIVE ,
       BANKNAME ,
       EFTBankAcct ,
       EFTBankBranch ,
       GIROPostType ,
       EFTBankCode ,
       EFTBankBranchCode ,
       EFTBankCheckDigit ,
       BSROLLNO ,
       IntlBankAcctNum ,
       SWIFTADDR ,
       CustVendCountryCode ,
       DeliveryCountryCode ,
       BNKCTRCD ,
       CBANKCD ,
       ADDRESS1 ,
       ADDRESS2 ,
       ADDRESS3 ,
       ADDRESS4 ,
       RegCode1 ,
       RegCode2 ,
       BankInfo7 ,
       EFTTransitRoutingNo ,
       CURNCYID ,
       EFTTransferMethod ,
       EFTAccountType ,
       EFTPrenoteDate ,
       EFTTerminationDate	 FROM EMPL_BANK_BACKUP_SY0600 WHERE VENDORID = 'HALLAHAN'


SELECT SERIES ,
       CustomerVendor_ID ,
       ADRSCODE ,
       VENDORID ,
       CUSTNMBR ,
       EFTUseMasterID ,
       EFTBankType ,
       FRGNBANK ,
       INACTIVE ,
       BANKNAME ,
       EFTBankAcct ,
       EFTBankBranch ,
       GIROPostType ,
       EFTBankCode ,
       EFTBankBranchCode ,
       EFTBankCheckDigit ,
       BSROLLNO ,
       IntlBankAcctNum ,
       SWIFTADDR ,
       CustVendCountryCode ,
       DeliveryCountryCode ,
       BNKCTRCD ,
       CBANKCD ,
       ADDRESS1 ,
       ADDRESS2 ,
       ADDRESS3 ,
       ADDRESS4 ,
       RegCode1 ,
       RegCode2 ,
       BankInfo7 ,
       EFTTransitRoutingNo ,
       CURNCYID ,
       EFTTransferMethod ,
       EFTAccountType ,
       EFTPrenoteDate ,
       EFTTerminationDate ,
       DEX_ROW_ID FROM dbo.SY06000