

select s.* INTO EPCO.dbo.EMPL_BANK_BACKUP_SY0600 FROM SY01200 p
join SY06000 s on s.VENDORID  = p.Master_ID
WHERE VENDORID IN  (SELECT VendorID FROM pm00200 WHERE VENDSTTS = 1 AND VNDCLSID = 'EMPEXP')

--(SELECT vendorID FROM pm00200 p2 WHERE p2.VENDSTTS = 1)

-- For employees where vendorID in (SELECT VendorID FROM pm00200 WHERE VENDSTTS = 1 AND VNDCLSID = 'EMPEXP')

-- for stuck EFT batches select * FROM dbo.cm20203
-- INTO EPCO.dbo.EMPL_BANK_BACKUP

--SELECT * FROM dbo.SY01200