DECLARE @products TABLE
    (
      [ProductCode] [NVARCHAR](2) NOT NULL ,
      [Name] [NVARCHAR](40) NOT NULL
    );

DECLARE @Market TABLE
    (
      [Market] NVARCHAR(30) ,
      [OrgDest] VARCHAR(3)
    );
DECLARE @Desig TABLE
    (
      [ProductCode] NVARCHAR(2) ,
      [Desig] NVARCHAR(30)
    );

INSERT INTO @products
        ( ProductCode, Name )
SELECT '10','Isomerized Naphtha' UNION ALL
SELECT '11','Naphtha (Sour)' UNION ALL
SELECT '12','Naphtha' UNION ALL
SELECT '13','Naph/U/L Blend' UNION ALL
SELECT '14','Natural Gasoline' UNION ALL
SELECT '15','Blend Grade Gas' UNION ALL
SELECT '16','Reformate' UNION ALL
SELECT '17','Iso Octane' UNION ALL
SELECT '18','Raffinate' UNION ALL
SELECT '19','HUF/Toluene' UNION ALL
SELECT '1A','Low Sulfur Natural Gasoline' UNION ALL
SELECT '1B','High Sulfur Natural Gasoline' UNION ALL
SELECT '20','EPL METER USE' UNION ALL
SELECT '21','U/L Prem-Gas FG-1' UNION ALL
SELECT '22','U/L Prem-N/O WPL-A' UNION ALL
SELECT '23','U/L Prem-N/O WPL-A1' UNION ALL
SELECT '24','FUTURE' UNION ALL
SELECT '25','U/L Prem-Gas FG-1' UNION ALL
SELECT '26','Conv Prem-Region 2' UNION ALL
SELECT '27','U/L Prem-Gas FG-1' UNION ALL
SELECT '28','U/L Prem-Gas Seg.' UNION ALL
SELECT '29','U/L Prem-Gas FG-1' UNION ALL
SELECT '2A','RFG VOC1-CM-Prem-GAS' UNION ALL
SELECT '2B','RFGNVOC1-CM-Prem-GAS' UNION ALL
SELECT '2C','FUTURE' UNION ALL
SELECT '2D','FUTURE' UNION ALL
SELECT '2N','RFG VOC2-CM-Prem-GAS' UNION ALL
SELECT '2P','RFGNVOC2-CM-Prem-GAS' UNION ALL
SELECT '2Q','FUTURE' UNION ALL
SELECT '2R','FUTURE' UNION ALL
SELECT '2S','FUTURE' UNION ALL
SELECT '2T','FUTURE' UNION ALL
SELECT '2U','RFG VOC2-RBOB-CEBLND' UNION ALL
SELECT '2V','RFGNVOC2-RBOB-CEBLND' UNION ALL
SELECT '2W','RFG VOC2-RBOB-CABLND' UNION ALL
SELECT '2X','RFGNVOC2-RBOB-CABLND' UNION ALL
SELECT '2Y','FUTURE' UNION ALL
SELECT '2Z','RFGNVOC2-RBOB-CABLND' UNION ALL
SELECT '30','FUTURE' UNION ALL
SELECT '31','U/L Prem-Gas FG-1' UNION ALL
SELECT '32','U/L Prem-N/O WPL-A' UNION ALL
SELECT '33','U/L Prem-N/O WPL-A-1' UNION ALL
SELECT '34','U/L Prem-Gas Seg' UNION ALL
SELECT '35','U/L Prem-Gas FG-1' UNION ALL
SELECT '36','U/L Prem-Gas Seg' UNION ALL
SELECT '37','U/L Prem-Gas FG-1' UNION ALL
SELECT '38','U/L Prem-Gas Seg' UNION ALL
SELECT '39','U/L Prem-Gas FG-1' UNION ALL
SELECT '3A','RFG  VOC1-CM-Pm-GAS' UNION ALL
SELECT '3B','RFG NVOC1-CM-Pm-GAS' UNION ALL
SELECT '3C','PBOBVOC1-CM-BlendStock' UNION ALL
SELECT '3D','PBOB NVOC1-CM-BlendStock' UNION ALL
SELECT '3F','RFG  VOC1-CM-Pm-GAS' UNION ALL
SELECT '3G','RFGNVOC1-CM-Prem-Gas' UNION ALL
SELECT '3K','U/L Prem-Gas Seg' UNION ALL
SELECT '3L','RFGNVOC1-CM-Prem-Gas' UNION ALL
SELECT '3N','RFG  VOC2-CM-PM-GAS' UNION ALL
SELECT '3P','RFG NVOC2-CM-PM-GAS' UNION ALL
SELECT '3R','PBOB' UNION ALL
SELECT '3S','RBOB' UNION ALL
SELECT '3T','RBOB' UNION ALL
SELECT '3U','RFG VOC2 RBOB-CABLND' UNION ALL
SELECT '3W','RFG  VOC2RBOB-CABLND' UNION ALL
SELECT '3X','RFG NVOC2RBOB-CABLND' UNION ALL
SELECT '3Z','RFG  VOC2RBOB-CABLND' UNION ALL
SELECT '40','U/L Reg-Gas WPL-A2' UNION ALL
SELECT '41','U/l Reg-Gas FG-1' UNION ALL
SELECT '42','U/L Reg-N/O WPL-N' UNION ALL
SELECT '43','U/L Reg-N/O WPL-N1' UNION ALL
SELECT '44','U/L Reg-Gas FG-2' UNION ALL
SELECT '45','U/L Reg-Gas Seg' UNION ALL
SELECT '46','U/L Reg-Gas FG-2' UNION ALL
SELECT '47','U/L Reg-Gas Seg' UNION ALL
SELECT '48','Reprocessed U/L Gas' UNION ALL
SELECT '49','Specialty Grade Buffer' UNION ALL
SELECT '4A','RFG  VOC1-CM-GAS' UNION ALL
SELECT '4B','RFG NVOC1-CM-GAS' UNION ALL
SELECT '4C','RBOB VOC1-CM-BlendStock' UNION ALL
SELECT '4D','RBOB NVOC1-CM-Blend Stock' UNION ALL
SELECT '4F','RFG VOC1 REG.GAS' UNION ALL
SELECT '4G','RFG NVOC1 REG.GAS' UNION ALL
SELECT '4H','RFG VOC1-CM-REG' UNION ALL
SELECT '4N','RFG  VOC2-CM-GAS' UNION ALL
SELECT '4P','RFG NVOC2-CM-GAS' UNION ALL
SELECT '4S','RFG VOC2-RBOB-CABLND' UNION ALL
SELECT '4T','RBOB' UNION ALL
SELECT '4U','RFG VOC2-RBOB-CEBLND' UNION ALL
SELECT '4V','RFGNVOC2-RBOB-CEBLND' UNION ALL
SELECT '4W','RFG VOC2-RBOB-CABLND' UNION ALL
SELECT '4X','RFGNVOC2-RBOB-CABLND' UNION ALL
SELECT '4Y','RFG VOC2-RBOB-CABLND' UNION ALL
SELECT '4Z','RFGNVOC2-RBOB-CABLND' UNION ALL
SELECT '50','JP-8 Military Jet' UNION ALL
SELECT '51','Jet Fuel A .30S FJ-1' UNION ALL
SELECT '52','Jet Fuel A     WPL-Q' UNION ALL
SELECT '53','Jet Fuel A-1 Seg' UNION ALL
SELECT '54','Jet Fuel Bonded FJ-2' UNION ALL
SELECT '55','K2-Kero .30S     Dye' UNION ALL
SELECT '56','K1-Kero .04S' UNION ALL
SELECT '57','JP-4 Blend Stock' UNION ALL
SELECT '58','Jet Fuel JP-4' UNION ALL
SELECT '59','J-40 Jet-A Buff-Stk' UNION ALL
SELECT '60','FUTURE' UNION ALL
SELECT '62','No.1 F/O .047S WPL-Y' UNION ALL
SELECT '64','ULSD Kerosene for blending ULSD only' UNION ALL
SELECT '6Y','ULSD KEROSENE' UNION ALL
SELECT '70','Future' UNION ALL
SELECT '71','Texas L S Dsl.047S UnDyed' UNION ALL
SELECT '72','WPL LSD .047 Off Road UnD' UNION ALL
SELECT '73','WPL LSD .047 On Road' UNION ALL
SELECT '74','Lo S Dsl.  .047S (Locomotive and Marine)' UNION ALL
SELECT '75','ULSD On Road' UNION ALL
SELECT '76','Transitional ULSD' UNION ALL
SELECT '77','ULSD TX LED Blend' UNION ALL
SELECT '78','Reprocessed No.2 F/O' UNION ALL
SELECT '79','ULSD - Payback Barrels' UNION ALL
SELECT '7A','LSD Off Road undyed' UNION ALL
SELECT '7B','ULSD with 5% BioDiesel' UNION ALL
SELECT '7C','ULSD Texas LED' UNION ALL
SELECT '7H','Magellan High Sulfer Diesel No. 2' UNION ALL
SELECT '7R','WPL ULSD 40C Off Road' UNION ALL
SELECT '7T','WPL ULSD 40C Transitional' UNION ALL
SELECT '7V','ULSD Off Road' UNION ALL
SELECT '7W','ULSD TX Low Transitional' UNION ALL
SELECT '7X','No.2FO 40C WPL ULSD OnRd' UNION ALL
SELECT '80','Lt. Cycle Oil UnDyed' UNION ALL
SELECT '81','Unfinished Dist.' UNION ALL
SELECT '82','None' UNION ALL
SELECT '84','FUTURE' UNION ALL
SELECT '86','FUTURE' UNION ALL
SELECT '89','FUTURE' UNION ALL
SELECT '90','Transmix Generated' UNION ALL
SELECT '91','Transmix B' UNION ALL
SELECT '92','TMX Price' UNION ALL
SELECT '93','Transmix Sold' UNION ALL
SELECT '95','Transmix' UNION ALL
SELECT '96','Transmix' UNION ALL
SELECT '97','Transmix' UNION ALL
SELECT '98','Transmix Sold - New' UNION ALL
SELECT '99','Transmix Sold' UNION ALL
SELECT '9A','Assigned Transmix' UNION ALL
SELECT '3E','U/L PREM Conventional' UNION ALL
SELECT '3V','PBOB - Prem Gas Blndstk - St Louis Area' UNION ALL
SELECT '4E','U/L REG Conventional' UNION ALL
SELECT '7D','ULSD Buffer for Diluent' UNION ALL
SELECT '4J','RFG-VOC1-OCM-REG TEXAS' UNION ALL
SELECT '4K','Sub Octane Blend Stock' UNION ALL
SELECT '1E','Naphtha With NODRA' UNION ALL
SELECT '4M','Sub Octane' UNION ALL
SELECT '1C','Condensate Segregated' UNION ALL
SELECT 'PP','Product Passthrough Storage' UNION ALL
SELECT '7E','TXLED with 5% Bio Diesel' UNION ALL
SELECT '3_','Premium Discount' UNION ALL
SELECT '9Z','ULST Ultra Low Sulfur Transmix' 

INSERT INTO @Desig
        ( ProductCode, Desig )
SELECT '10','Other' UNION ALL
SELECT '11','Other' UNION ALL
SELECT '12','Other' UNION ALL
SELECT '13','Other' UNION ALL
SELECT '14','Other' UNION ALL
SELECT '15','Other' UNION ALL
SELECT '16','Other' UNION ALL
SELECT '17','Other' UNION ALL
SELECT '18','Other' UNION ALL
SELECT '19','Other' UNION ALL
SELECT '1A','Diluent' UNION ALL
SELECT '1B','Diluent' UNION ALL
SELECT '1C','Diluent' UNION ALL
SELECT '1E','Other' UNION ALL
SELECT '21','Gasoline' UNION ALL
SELECT '22','Gasoline' UNION ALL
SELECT '24','Gasoline' UNION ALL
SELECT '26','Gasoline' UNION ALL
SELECT '28','Gasoline' UNION ALL
SELECT '31','Gasoline' UNION ALL
SELECT '32','Gasoline' UNION ALL
SELECT '33','Gasoline' UNION ALL
SELECT '34','Gasoline' UNION ALL
SELECT '35','Gasoline' UNION ALL
SELECT '36','Gasoline' UNION ALL
SELECT '37','Gasoline' UNION ALL
SELECT '38','Gasoline' UNION ALL
SELECT '3C','Gasoline' UNION ALL
SELECT '3D','Gasoline' UNION ALL
SELECT '3E','Gasoline' UNION ALL
SELECT '3R','Gasoline' UNION ALL
SELECT '3S','Gasoline' UNION ALL
SELECT '3T','Gasoline' UNION ALL
SELECT '3U','Gasoline' UNION ALL
SELECT '3V','Gasoline' UNION ALL
SELECT '3X','Gasoline' UNION ALL
SELECT '3Z','Gasoline' UNION ALL
SELECT '40','Gasoline' UNION ALL
SELECT '41','Gasoline' UNION ALL
SELECT '42','Gasoline' UNION ALL
SELECT '43','Gasoline' UNION ALL
SELECT '44','Gasoline' UNION ALL
SELECT '45','Gasoline' UNION ALL
SELECT '46','Gasoline' UNION ALL
SELECT '47','Gasoline' UNION ALL
SELECT '48','Gasoline' UNION ALL
SELECT '49','Gasoline' UNION ALL
SELECT '4C','Gasoline' UNION ALL
SELECT '4D','Gasoline' UNION ALL
SELECT '4E','Gasoline' UNION ALL
SELECT '4F','Gasoline' UNION ALL
SELECT '4G','Gasoline' UNION ALL
SELECT '4H','Gasoline' UNION ALL
SELECT '4J','Gasoline' UNION ALL
SELECT '4K','Gasoline' UNION ALL
SELECT '4M','Gasoline' UNION ALL
SELECT '4S','Gasoline' UNION ALL
SELECT '4T','Gasoline' UNION ALL
SELECT '4U','Gasoline' UNION ALL
SELECT '4X','Gasoline' UNION ALL
SELECT '50','Jet' UNION ALL
SELECT '51','Jet' UNION ALL
SELECT '52','Jet' UNION ALL
SELECT '54','Jet' UNION ALL
SELECT '56','Jet' UNION ALL
SELECT '57','Jet' UNION ALL
SELECT '59','Jet' UNION ALL
SELECT '62','Diesel' UNION ALL
SELECT '64','Diesel' UNION ALL
SELECT '6Y','Diesel' UNION ALL
SELECT '74','Diesel' UNION ALL
SELECT '75','Diesel' UNION ALL
SELECT '77','Diesel' UNION ALL
SELECT '79','Diesel' UNION ALL
SELECT '7B','Diesel' UNION ALL
SELECT '7C','Diesel' UNION ALL
SELECT '7D','Diesel' UNION ALL
SELECT '7E','Diesel' UNION ALL
SELECT '7R','Diesel' UNION ALL
SELECT '7V','Diesel' UNION ALL
SELECT '7X','Diesel' UNION ALL
SELECT '80','Other' UNION ALL
SELECT '90','Other' UNION ALL
SELECT '92','Other' UNION ALL
SELECT '94','Other' UNION ALL
SELECT '96','Other' UNION ALL
SELECT '97','Other' 

INSERT INTO @Market
        ( Market, OrgDest )
SELECT 'AND','Houston' UNION ALL
SELECT 'ALD','Houston' UNION ALL
SELECT 'ARL','Dallas' UNION ALL
SELECT 'BRN','Houston' UNION ALL
SELECT 'CED','Houston' UNION ALL
SELECT 'DAL','Dallas' UNION ALL
SELECT 'DFW','Dallas' UNION ALL
SELECT 'ESL','St Louis' UNION ALL
SELECT 'FNA','Houston' UNION ALL
SELECT 'FOR','Dallas' UNION ALL
SELECT 'FWM','Dallas' UNION ALL
SELECT 'FWT','Dallas' UNION ALL
SELECT 'GLN','Tulsa' UNION ALL
SELECT 'GRF','Chicago' UNION ALL
SELECT 'GRP','Dallas' UNION ALL
SELECT 'GVL','Dallas' UNION ALL
SELECT 'HMD','Chicago' UNION ALL
SELECT 'HOU','Houston' UNION ALL
SELECT 'HRT','Houston' UNION ALL
SELECT 'IRW','Chicago' UNION ALL
SELECT 'IRV','Dallas' UNION ALL
SELECT 'MTV','Tulsa' UNION ALL
SELECT 'NHO','Houston' UNION ALL
SELECT 'NPA','Houston' UNION ALL
SELECT 'PTA','Houston' UNION ALL
SELECT 'PTN','Houston' UNION ALL
SELECT 'PAS','Houston' UNION ALL
SELECT 'STL','St Louis' UNION ALL
SELECT 'STP','St Louis' UNION ALL
SELECT 'TUW','Tulsa' UNION ALL
SELECT 'WAC','Dallas' UNION ALL
SELECT 'WDR','St Louis' UNION ALL
SELECT 'WYN','Houston' 

     
     



SELECT  Shipper ,
        Product ,
		p.Name AS [Product Name],
        origin ,
        MeterName AS Meter ,
        Location ,
        netVol ,
        custody ,
        ReceiptDelivery ,
        ConnectionCode ,
        DATEPART(YEAR, DATEADD(SECOND, endTime, '1970-1-1')) AS [Year] ,
        DATEPART(QUARTER, DATEADD(SECOND, endTime, '1970-1-1')) AS [Quarter]
		DATEPART(MONTH, DATEADD(SECOND, endTime, '1970-1-1')) AS [Month]
FROM    dbo.tbl_ticket t
JOIN @products p ON p.ProductCode = t.product
LEFT OUTER JOIN @Desig d ON d.ProductCode = p.ProductCode
LEFT OUTER JOIN @Market mOrg ON mOrg.OrgDest = t.origin
LEFT OUTER JOIN @Market mLoc ON mLoc.OrgDest = t.location
WHERE    DATEPART(YEAR,GETDATE()) - DATEPART(DATEADD(SECOND, endTime, '1970-1-1'),Year) <=3
ORDER BY DATEPART(YEAR, DATEADD(SECOND, endTime, '1970-1-1')) ,
        DATEPART(QUARTER, DATEADD(SECOND, endTime, '1970-1-1')); 


