/* *******************************************************
SPL
******************************************************* */
--UPDATE		InvoiceDetails
--SET			TicketNumber = 'HT-3'
--WHERE		TicketNumber = '3'
--AND			YEAR( EndDate ) = 2016

/* *******************************************************
MAC
******************************************************* */
DECLARE @Shipper [varchar](3); SET @Shipper = 'MAC'
DECLARE @InvoiceDate [date]; SET @InvoiceDate = '2016-11-3'
DECLARE @PeriodOfService [varchar](50); SET @PeriodOfService = '10/16/2016 TO 10/31/2016'
DECLARE @BillTo [varchar](3); SET @BillTo = 'MAC'
DECLARE @CurrentInvoiceId [int]
DECLARE @NewInvoiceId [int]

SET @CurrentInvoiceID = ( 
						SELECT		InvoiceID
						FROM		InvoiceHeaders
						WHERE		Shipper = @Shipper
						AND			PeriodOfService = @PeriodOfService
						AND			BillTo = @BillTo
						)
						
SELECT	InvoiceID
FROM	InvoiceHeaders
WHERE	Shipper = @Shipper
AND		PeriodOfService = @PeriodOfService
AND		BillTo = @BillTo
IF		@@ROWCOUNT = 1
BEGIN
	INSERT INTO [dbo].[InvoiceHeaders] ([InvoiceTypeID], [InvoiceNumber], [Shipper], [InvoiceDate], [PeriodOfService], [BillTo], [TransmittedToGP], [AutoGenerated]) VALUES ( '1', 'Pending', @Shipper, @InvoiceDate, @PeriodOfService, @BillTo, '0', '1' )
	SET @NewInvoiceId = CAST( SCOPE_IDENTITY() AS INT )

	UPDATE		InvoiceDetails
	SET			InvoiceID = @NewInvoiceID
	WHERE		InvoiceID = @CurrentInvoiceID
	AND			ProductCode = '45' END



