/*
-- On the old server DBSVR..EPCO, before Drew creates the depreciation batch using the Property application, clear out last month's batch:
delete from sy00500 where bachnumb = 'DEPR_IMPORT'
delete from gl10000 where bachnumb = 'DEPR_IMPORT'
delete from gl10001 where bachnumb = 'DEPR_IMPORT'
*/
-- Have Drew enter date 
-- On the new server DBSVR-PCC..EPCO, get the next available journal entry number:
DECLARE @NJRNLENT int
SET @NJRNLENT = (SELECT NJRNLENT FROM GL40000)
UPDATE GL40000 SET NJRNLENT = NJRNLENT + 1
SELECT @NJRNLENT
-- Back on the old server, plug the new server's next journal entry number into the data sets:
DECLARE @NJRNLENT int
SET @NJRNLENT = 454186
SELECT GLPOSTDT, BCHSOURC, BACHNUMB, SERIES, MKDTOPST, NUMOFTRX, RECPSTGS, DELBACH, MSCBDINC, BACHFREQ, RCLPSTDT, NOFPSTGS, BCHCOMNT, BRKDNALL, CHKSPRTD, RVRSBACH, USERID, CHEKBKID
, BCHTOTAL, BCHEMSG1, BCHEMSG2, BACHDATE, BCHSTRG1, BCHSTRG2, POSTTOGL, MODIFDT, CREATDDT, NOTEINDX, CURNCYID, BCHSTTUS, CNTRLTRX, CNTRLTOT, PETRXCNT, APPROVL, APPRVLDT, APRVLUSERID, 
ORIGIN, ERRSTATE, GLBCHVAL, Computer_Check_Doc_Date, Sort_Checks_By, SEPRMTNC, REPRNTED, CHKFRMTS, TRXSORCE, PmtMethod, EFTFileFormat, Workflow_Approval_Status, Workflow_Priority, 
TIME1, 0 ClearRecAmts, 0 PurchasingPrepaymentBch FROM SY00500 WHERE BACHNUMB = 'DEPR_IMPORT'

SELECT BACHNUMB, BCHSOURC, @NJRNLENT JRNENTRY, RCTRXSEQ, SOURCDOC, REFRENCE, TRXDATE, RVRSNGDT, RCRNGTRX, BALFRCLC, PSTGSTUS, LASTUSER, LSTDTEDT, USWHPSTD, TRXTYPE, SQNCLINE, GLHDRMSG, 
GLHDRMS2, TRXSORCE, RVTRXSRC, SERIES, ORPSTDDT, ORTRXSRC, OrigDTASeries, DTAControlNum, DTATRXType, DTA_Index, CURNCYID, 0 CURRNIDX, RATETPID, EXGTBLID, XCHGRATE, EXCHDATE, TIME1, 
RTCLCMTD, NOTEINDX, GLHDRVAL, PERIODID, OPENYEAR, CLOSEDYR, HISTRX, REVPRDID, REVYEAR, REVCLYR, REVHIST, ERRSTATE, ICTRX, ORCOMID, ORIGINJE, ICDISTS, PRNTSTUS, DENXRATE, MCTRXSTT, DOCDATE,
 Tax_Date, VOIDED, Original_JE, Original_JE_Year, Original_JE_Seq_Num, Correcting_Trx_Type, 1 Ledger_ID, 0 Adjustment_Transaction, DEX_ROW_TS FROM GL10000 WHERE BACHNUMB = 'DEPR_IMPORT'

SELECT BACHNUMB, @NJRNLENT JRNENTRY, SQNCLINE, ACTINDX, XCHGRATE, DSCRIPTN, GLLINMSG, GLLINMS2, CURRNIDX, GLLINVAL, ACCTTYPE, FXDORVAR, BALFRCLC, PSTNGTYP, DECPLACS, ORCTRNUM, ORDOCNUM, 
ORMSTRID, ORMSTRNM, ORTRXTYP, OrigSeqNum, ORTRXDESC, DTA_GL_Status, INTERID, RATETPID, EXGTBLID, EXCHDATE, TIME1, RTCLCMTD, CRDTAMNT, DEBITAMT, ORCRDAMT, ORDBTAMT, DENXRATE, MCTRXSTT, LNESTAT, 
CorrespondingUnit, '2013-10-11 15:57:03.703' DEX_ROW_TS FROM GL10001  where BACHNUMB = 'DEPR_IMPORT'
-- Back on the new server, open the tables using "Edit Top 200 Rows". 